### ISSUE TITLE
After building an image that was built before, a dangling <none> remains

### ISSUE THREAD

**Issue by remmelt** [wouterd/docker-maven-plugin#51]
Reproduce this by:

1) building an image, note that it gets added to the list in `docker images`
2) build the same image again, with the same tag.

The previous image gets untagged but not deleted. This results in a dangling image.

Can the previous image be deleted automatically?

I am using OSX with boot2docker.

```
$ boot2docker version                                                                                                                                                                             
Boot2Docker-cli version: v1.3.0
Git commit: deafc19
```
```
$ docker --version                                                                                                                                                                                
Docker version 1.3.0, build c78088f
```

**Comment by wouterd** [comment]
Closing this, because it's really standard docker behavior and it's fixable by running a simple cron job on the docker host that runs `docker rmi $(docker images -qa -f "dangling=true")`

**Comment by danilaml** [comment]
Sorry for a bif of the necropost, but the suggested solution is not really beautiful (and sometimes needs plastering sudo's all over the place). Would be nice if docker provided this functionality out-of-the box (something akin to `git commit --amend`). It'd be especially useful when you have relatively big docker images and in the process of the rapid "tinker a bit with dockerfile/required files" -> docker build -> docker run and repeat. Disk space disappears very fast.

**Comment by evbarnett** [comment]
I know this thread is out of date- but I would like to voice my support for some kind of basic "garbage collection" to remove the useless, dangling images.

**Comment by yasassri** [comment]
@wouterd Did you guys consider the above and did any implementation?

**Comment by Lewiscowles1986** [comment]
in my `~/.bashrc` I ensure the following lines are present

```
alias docker_rm_all="docker rm \`docker ps -a -q\`"
alias docker_rmi_all="docker rmi \`docker images -q\`"
alias docker_rmi_dangling="docker rmi \`docker images -qa -f 'dangling=true'\`"
```

This allows me to clear all containers, all images, and all dangling images. Seems to fulfil this and a few other issues

**Comment by yallanki9160** [comment]
The above command should not work for me in my mac os
