### ISSUE TITLE
Pushing should be done at the end of a multi-module build

### ISSUE THREAD

**Issue by remmelt** [wouterd/docker-maven-plugin#56]
Currently, when pushing the built images to a remote docker registry in a multi-module build, each module builds, then immediately pushes its Docker image to the registry.

When a module in the middle fails to build, no images should have been pushed.

I could not find a way to achieve this, although the plugin suggests it can be done, using the `push` tag in the `build-images` goal, then doing the actual pushing in a different phase.

**Comment by wouterd** [comment]
Hi!

#100 should be able to help you here. Just create a separate module that depends on the artifacts that can fail. Then use the maven-dependency trick to get the built artifacts into your docker images.
