### ISSUE TITLE
Build status report

### ISSUE THREAD

**Issue by helander** [wouterd/docker-maven-plugin#62]
Is it possible to be informed about failures that occur during image build?
Preferably being able to terminate the maven build if an error occurs during Dockerfile "execution".
It would also be great to see the output from the individual Dockerfile lines.

As of now I have to use "docker build ..." explicitly (including having to put all input file under one directory) in order to make sure that my image builds OK.

**Comment by wouterd** [comment]
Sorry for the way too late reply.
I'd love to incorporate this, but I ran into issues trying this earlier.
Currently working on fixing the integration tests with docker versions 1.4+, will look into this again after.
