### ISSUE TITLE
fail starting containers

### ISSUE THREAD

**Issue by arthurtsang** [wouterd/docker-maven-plugin#64]
I've program starting the containers with the plugin

# mvn docker:start-containers
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building search-svc 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- docker-maven-plugin:3.0:start-containers (default-cli) @ search-svc ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.327 s
[INFO] Finished at: 2015-03-19T22:41:36-07:00
[INFO] Final Memory: 9M/238M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:3.0:start-containers (default-cli) on project search-svc: The parameters 'containers' for goal net.wouterdanes.docker:docker-maven-plugin:3.0:start-containers are missing or invalid -> [Help 1]

# here's the config
```
<execution>
                        <id>start</id>
                        <goals>
                            <goal>start-containers</goal>
                        </goals>
                        <configuration>
                            <containers>
                                <container>
                                    <image>${project.name}:${project.version}</image>
                                </container>
                            </containers>
                        </configuration>
                    </execution>
```

# maven version
mvn --version
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T06:51:42-07:00)
Maven home: /opt/apache-maven-3.2.2
Java version: 1.8.0_40, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-31-generic", arch: "amd64", family: "unix"

however, it can start & stop the container through the verify goal.  

# mvn verify

[INFO] --- docker-maven-plugin:3.0:build-images (build) @ search-svc ---
[INFO] Using docker provider: remote
[INFO] Building image 'search', with name and tag 'search-svc:1.0-SNAPSHOT'..
[INFO] Image 'search' has Id 'cf3e355fc5ce'
[INFO] 
[INFO] --- docker-maven-plugin:3.0:start-containers (start) @ search-svc ---
[INFO] Using docker provider: remote
[INFO] Starting container 'search-svc:1.0-SNAPSHOT'..
[INFO] Setting property 'docker.containers.search-svc:1.0-SNAPSHOT.ports.8080/tcp.host' to '127.0.0.1'
[INFO] Setting property 'docker.containers.search-svc:1.0-SNAPSHOT.ports.8080/tcp.port' to '49155'
[INFO] Started container with id '77103f93ef186e6bb5b1812979176bdac57b66f7c263cc6483a1262d2dd2dc07'
[INFO] 
[INFO] --- docker-maven-plugin:3.0:stop-containers (stop) @ search-svc ---
[INFO] Using docker provider: remote
[INFO] Stopping container '77103f93ef186e6bb5b1812979176bdac57b66f7c263cc6483a1262d2dd2dc07'..
[INFO] Deleting container '77103f93ef186e6bb5b1812979176bdac57b66f7c263cc6483a1262d2dd2dc07'..
[INFO] Keeping image cf3e355fc5ce
[INFO] 
[INFO] --- docker-maven-plugin:3.0:verify (verify) @ search-svc ---
[INFO] Using docker provider: remote

**Comment by wouterd** [comment]
Hmm, try moving the configuration outside the execution block, but in the root of the plugin definition. Does that help? I think the configuration in the execution block is only visible in the phase where that goal is registeren, which is "pre-integration-test" by default.

**Comment by arthurtsang** [comment]
yes, it  works!  thanks
