### ISSUE TITLE
Tagging task is failing / manual tagging with -f fixing

### ISSUE THREAD

**Issue by aykutyararbas** [wouterd/docker-maven-plugin#65]
##docker version

Client version: 1.5.0-dev
Client API version: 1.18
Go version (client): go1.3.1
Git commit (client): fc0329b/1.5.0
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.1
Git commit (server): fc0329b/1.5.0
OS/Arch (server): linux/amd64

##Plugin version 3.0 

###Issue
18:38:48 [ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:3.0:tag-images (release) on project kafka: Failed to add tag 'a1f22d36d8ed' to image 'bmcgeneva:kafka-1.0.0-SNAPSHOT-latest': Conflict -> [Help 1]

### Manual tagging is working with -f option
docker tag -f a1f22d36d8ed bmcgeneva:kafka-1.0.0-SNAPSHOT-latest

Any ideas ? Is it the version a problem ?

**Comment by lcoote** [comment]
could you post your POM configuration. 

your error message seems the wrong way around. This would make more sense:

Failed to add tag '**bmcgeneva:kafka-1.0.0-SNAPSHOT-latest**' to image '**a1f22d36d8ed**'

This could easily be a fault in the logging though, and a red herring.

**Comment by wouterd** [comment]
Hi there!
The newest version of the plugin (3.1.0 as of this writing) now forces the tagging and I fixed the error message as well. Thanks for the heads-up.

**Comment by aykutyararbas** [comment]
Thanks a lot ,
I'll switch to latest version.
