### ISSUE TITLE
Exposed ports question

### ISSUE THREAD

**Issue by nickcodefresh** [wouterd/docker-maven-plugin#68]
Can you clarify what is meant by:

>By default, all exposed ports are published on the host. The following two properties are set per exposed port:

>docker.containers.[id].ports.[portname].host (f.ex 'docker.containers.id.cache.ports.80/tcp.host')
>docker.containers.[id].ports.[portname].port (f.ex 'docker.containers.id.cache.ports.80/tcp.port')

>You can pass those project properties over to your integration test and use them to connect to your application.

How can I pass these properties in my test? Are they exposed as system properties?

Thanks

Nick

**Comment by wouterd** [comment]
They are exposed as project properties. You can pass them to your tests as such:
```
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.17</version>
                <configuration>
                    <systemProperties>
                        <app.base.1>http://${docker.containers.app.ports.8080/tcp.host}:${docker.containers.app.ports.8080/tcp.port}</app.base.1>
                        <app.base.2>http://${docker.containers.app2.ports.8080/tcp.host}:${docker.containers.app2.ports.8080/tcp.port}</app.base.2>
                    </systemProperties>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

See also: https://github.com/wouterd/docker-maven-plugin/blob/master/src/it/sample-api-mongo-it/pom.xml

**Comment by nickcodefresh** [comment]
Thanks for that
