### ISSUE TITLE
Socket support?

### ISSUE THREAD

**Issue by nickcodefresh** [wouterd/docker-maven-plugin#70]
I see that @Krijger created a fork to handle a socket provider. Any ideas where he is with this, and if it'll ever be committed back to the main repo?

**Comment by wouterd** [comment]
That never got finished, it's fairly hard to get unix sockets going in Java.
It's also quite hard to wire the transport of HTTP clients over a file socket instead of a tcp socket.
I think he gave up, I'll ask him Monday at work.
