### ISSUE TITLE
Show docker build output to see cache performance

### ISSUE THREAD

**Issue by icksa** [wouterd/docker-maven-plugin#72]
Hello:
Would it be possible to modify the plugin to show the docker build output? E.g...

```
Step 0 : FROM m-ubuntu
 ---> f898fb0ac394
Step 1 : MAINTAINER Steve
 ---> Using cache
 ---> 20341d993499
Step 2 : RUN apt-get update &&     apt-get install -y supervisor swift
 ---> Using cache
 ---> c63eb3d812e9
```

Currently, I don't think you can see this output even when doing a mvn build with debug output (-X). The reason I'd like to see this output is to see how well we are doing at preserving the cache. I'm afraid we have a few images that are not making good use of the docker cache and I'd like to have this output so I can more easily point it out to other developers...

Also, thanks for releasing 3.0.1!

**Comment by wouterd** [comment]
Thanks for the kind comment and great idea.
I'm going to release 3.1.0 right now that should give you the output that you want.
