### ISSUE TITLE
"Maven-like" behaviour for registry push

### ISSUE THREAD

**Issue by jarmoni** [wouterd/docker-maven-plugin#79]
As a Java-developer (and maven user) it would be quite cool if I could use a docker-registry in the same way as a Maven-Repostory: I want to push (immutable) releases and snapshot-versions which will be overwritten with the next deploy. Since docker-registry does not support this behaviour (every tag is immutable - except the tag 'latest'). Wouldn't it make sense to handle this client-side (inside docker-maven-plugin for example)?

If the plugin detects a snapshot, it checks if an image-tag with that name already exists and if so it will be removed before pushing the newly created snapshot to registry.

Imho this would make many things easier in a maven-driven-environment....

**Comment by wouterd** [comment]
Hi there!

Have you tried this with the latest version of the plugin? It should "force" tag images and thus overwrite the current tag if it already exists.
It will currently also overwrite non-snapshots, but that's kind of how docker works.
