### ISSUE TITLE
Minimum java release

### ISSUE THREAD

**Issue by moimael** [wouterd/docker-maven-plugin#91]
HI,

After merging this plugin in our master branch, I just discovered that this plugin needs java 8. It would be great to have a warning in the doc and even better to have a java 7 compatibility.

Thanks !

**Comment by wouterd** [comment]
Hi @moimael !
Sorry that the plugin is Java8, I thought it was about time to upgrade. :)

I'll add a notice to the docs, I don't plan on downgrading to Java7.

By the way: you can run maven under java8 and still compile java7 byte code, have a look at the maven-compiler-plugin. That might fix your issue too.

**Comment by moimael** [comment]
Yep thanks a lot for the doc fix ;)
