### ISSUE TITLE
build-image failure on linux when using <artifacts><file> with long filename.  

### ISSUE THREAD

**Issue by edesdan** [wouterd/docker-maven-plugin#98]
I'm trying to use the plugin to build an image but I found a "bug" when using this kind of configuration:

```
 <artifact>
  <file>${project.basedir}/src/app/</file>
  <dest>src/app/</dest>
 </artifact>
```

The task fails with the following error:

> [ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:4.1.1:build-images (package) on project ghibli-events-tracker: Execution package of goal net.wouterdanes.docker:docker-maven-plugin:4.1.1:build-images failed: file name 'app/spmgr/modules/org/apache/activemq/main/META-INF/maven/org.apache.activemq/activemq-rar/pom.properties' is too long ( > 100 bytes) -> 

The problem seems to be related to the apache.commons.compress library used in the project.

A possible workaround/solution is to rebuild the plugin using the following dependency and setting and setting ```setLongFileMode(TarArchiveOutputStream.LONGFILE_GNU)``` for ```TarArchiveOutputStream``` in the ```RemoteApiBasedDockerProvider``` class:

```
    <!-- Needed to build tar.gz archives for the docker build engine -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-compress</artifactId>
      <version>1.10</version>
    </dependency>
```

```
 private static byte[] getTgzArchiveForFiles(final ImageBuildConfiguration image) {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (
                TarArchiveOutputStream tar = (TarArchiveOutputStream) new ArchiveStreamFactory().createArchiveOutputStream("tar", baos)
        ) {
            
           
            tar.setLongFileMode(TarArchiveOutputStream.LONGFILE_GNU);
```

More info about the issue on apache library here: https://issues.apache.org/jira/browse/NUTCH-1963.

Thanks for filling the gap between docker and maven! It could be good to have this fix on the master branch.

**Comment by wouterd** [comment]
Thanks for pointing this out, I'll fix it for 5.0.0.
